name: release

on:
  release:
    types: [created]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./alpine/Dockerfile.php82
            image: ghcr.io//erfantkerfan/laravel-docker-image:php82
          - dockerfile: ./alpine/Dockerfile.php82-node
            image: ghcr.io//erfantkerfan/laravel-docker-image:php82-node
          - dockerfile: ./alpine/Dockerfile.php83
            image: ghcr.io//erfantkerfan/laravel-docker-image:php83
          - dockerfile: ./alpine/Dockerfile.php83-node
            image: ghcr.io//erfantkerfan/laravel-docker-image:php83-node
          - dockerfile: ./alpine/Dockerfile.php84
            image: ghcr.io//erfantkerfan/laravel-docker-image:php84
          - dockerfile: ./alpine/Dockerfile.php84-node
            image: ghcr.io//erfantkerfan/laravel-docker-image:php84-node
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ${{ matrix.dockerfile }}
          tags: ${{ matrix.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
